security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    #enable_authenticator_manager: true
    encoders:
        App\Entity\User:
            algorithm: auto
        #App\Entity\Operator:
        #    algorithm: auto
        #App\Entity\Admin:
        #    algorithm: auto
    providers:
        user:
            entity: { class: App\Entity\User, property: email }
        #operator:
        #    entity: { class: App\Entity\Operator, property: email }
        #admin:
        #    entity: { class: App\Entity\Admin, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        #login:
        #    pattern: ^/api/login
        #    provider: user
        #    stateless: true
           #json_login:
           #    check_path: /api/login_check
           #    success_handler: lexik_jwt_authentication.handler.authentication_success
           #    failure_handler: lexik_jwt_authentication.handler.authentication_failure
        #api:
        #    pattern: ^/api
        #    stateless: true
        #    provider: user
        #    guard:
        #        authenticators:
        #            - lexik_jwt_authentication.jwt_token_authenticator
        #middle:
        #    pattern: ^/middle
        #    provider: operator
        #    logout:
        #        invalidate_session: true
        #        path: /middle/logout
        #        target: /
        #    guard:
        #        authenticators:
        #            - App\Security\Guard\OperatorAuthenticator
        #admin:
        #    pattern: ^/_easyadmin
        #    provider: admin
        #    logout:
        #        invalidate_session: true
        #        path: /_easyadmin/logout
        #        target: /_easyadmin/login
        #    guard:
        #        authenticators:
         #           - App\Security\Guard\AdminAuthenticator
        main:
            pattern: ^/user
            provider: user
            logout:
                invalidate_session: true
                path: /logout
                target: /
            guard:
                authenticators:
                    - App\Security\Guard\UserAuthenticator
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: PUBLIC_ACCESS }

            # - { path: ^/_easyadmin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/_easyadmin, role: ROLE_ADMIN }
       # - { path: ^/account, roles: ROLE_USER }
       # - { path: ^/middle/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/middle, roles: ROLE_OPERATOR }
       # - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    #access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
